packages:
  - apps/*
  - benchmarks/*
  - packages/*
  - packages/react-email/dev
  - playground

autoInstallPeers: true

minimumReleaseAge: 1440 # 24 hours

# This creates a lockfile for every git branch
gitBranchLockfile: true
mergeGitBranchLockfilesBranchPattern: 
  - main
  - canary
