packages:
  - .github/actions/*
  - apps/*
  - benchmarks/*
  - packages/*
  - packages/editor/examples
  - packages/react-email/dev
  - playground

catalog:
  '@babel/parser': 7.27.0
  '@babel/traverse': 7.27.0
  '@radix-ui/colors': 3.0.0
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-tooltip': 1.2.8
  '@react-email/components': 0.0.36
  '@responsive-email/react-email': 0.0.4
  '@scaleway/sdk': ^1
  '@types/babel__core': 7.20.5
  '@types/babel__traverse': 7.20.7
  '@types/css-tree': 2.3.11
  '@types/mime-types': 2.1.4
  '@types/node': 22.19.13
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.4
  commander: ^13.0.0
  esbuild: 0.27.3
  framer-motion: 12.23.22
  log-symbols: ^7.0.0
  next: 16.1.7
  nypm: 0.6.5
  ora: ^8.0.0
  postcss: 8.5.8
  prism-react-renderer: 2.4.1
  react: 19.0.0
  react-dom: 19.0.0
  resend: 6.4.0
  sonner: 2.0.7
  '@tailwindcss/postcss': ^4.1.18
  tailwindcss: ^4.1.18
  tinybench: 3.1.0
  tsdown: 0.19.0
  tsx: 4.21.0
  typescript: 5.9.3
  vite: 7.3.1
  yalc: 1.0.0-pre.53
  zod: 4.1.12

autoInstallPeers: true
