export type { IconProps } from './types';

export { AlignCenterIcon } from './align-center-icon';
export { AlignLeftIcon } from './align-left-icon';
export { AlignRightIcon } from './align-right-icon';
export { BoldIcon } from './bold-icon';
export { CaseUpperIcon } from './case-upper-icon';
export { CheckIcon, CheckIcon as Check } from './check-icon';
export { ChevronDownIcon, ChevronDownIcon as ChevronDown } from './chevron-down-icon';
export { CodeIcon, CodeIcon as Code } from './code-icon';
export { Columns2Icon, Columns2Icon as Columns2 } from './columns-2-icon';
export { Columns3Icon, Columns3Icon as Columns3 } from './columns-3-icon';
export { Columns4Icon, Columns4Icon as Columns4 } from './columns-4-icon';
export { ExternalLinkIcon } from './external-link-icon';
export { Heading1Icon, Heading1Icon as Heading1 } from './heading-1-icon';
export { Heading2Icon, Heading2Icon as Heading2 } from './heading-2-icon';
export { Heading3Icon, Heading3Icon as Heading3 } from './heading-3-icon';
export { ItalicIcon } from './italic-icon';
export { LinkIcon } from './link-icon';
export { ListIcon, ListIcon as List } from './list-icon';
export { ListOrderedIcon, ListOrderedIcon as ListOrdered } from './list-ordered-icon';
export { MousePointerIcon, MousePointerIcon as MousePointer } from './mouse-pointer-icon';
export { PencilIcon } from './pencil-icon';
export { Rows2Icon, Rows2Icon as Rows2 } from './rows-2-icon';
export { SplitSquareVerticalIcon, SplitSquareVerticalIcon as SplitSquareVertical } from './split-square-vertical-icon';
export { SquareCodeIcon, SquareCodeIcon as SquareCode } from './square-code-icon';
export { StrikethroughIcon } from './strikethrough-icon';
export { TextIcon, TextIcon as Text } from './text-icon';
export { TextQuoteIcon, TextQuoteIcon as TextQuote } from './text-quote-icon';
export { UnderlineIcon } from './underline-icon';
export { UnlinkIcon } from './unlink-icon';
