import { defineConfig } from 'tsup';

export default defineConfig([
  {
    dts: false,
    entry: ['./src/cli/index.ts'],
    format: ['cjs'],
    outDir: 'dist/cli',
  },
  {
    dts: true,
    entry: ['./src/package/index.browser.ts'],
    tsconfig: "./src/package/tsconfig.json",
    treeshake: true,
    noExternal: [
      /patched-tailwindcss\/.*/,
      /patched-postcss\/.*/,
      /postcss\/.*/,
      'dlv',
      'didyoumean',
      '@alloc/quick-lru',
      'patched-postcss-selector-parser',
      'postcss-selector-parser',
      'postcss-js',
      'postcss-nested',
      'cssesc',
      'camelcase-css',
    ],
    format: ['cjs', 'esm'],
    outDir: 'dist',
  },
  {
    dts: true,
    entry: ['./src/package/index.node.ts'],
    tsconfig: "./src/package/tsconfig.json",
    treeshake: true,
    noExternal: [
      /patched-tailwindcss\/.*/,
      /patched-postcss\/.*/,
      /postcss\/.*/,
      'dlv',
      'didyoumean',
      '@alloc/quick-lru',
      'patched-postcss-selector-parser',
      'postcss-selector-parser',
      'postcss-js',
      'postcss-nested',
      'cssesc',
      'camelcase-css',
    ],
    format: ['cjs', 'esm'],
    outDir: 'dist',
  },
]);
