import { defineTheme } from './_helper.js';

export const baseAteliersulphurpoolLight = defineTheme({
  name: 'base-ateliersulphurpool-light',
  type: 'light',
  base: {
    fontFamily:
      'Consolas, Menlo, Monaco, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", "Courier New", Courier, monospace',
    fontSize: '14px',
    lineHeight: '1.375',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    background: '#f5f7ff',
    color: '#5e6687',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
  },
  palette: {
    comment: { color: '#898ea4' },
    prolog: { color: '#898ea4' },
    doctype: { color: '#898ea4' },
    cdata: { color: '#898ea4' },
    punctuation: { color: '#5e6687' },
    operator: { color: '#c76b29' },
    boolean: { color: '#c76b29' },
    number: { color: '#c76b29' },
    property: { color: '#c08b30' },
    tag: { color: '#3d8fd1' },
    string: { color: '#22a2c9' },
    selector: { color: '#6679cc' },
    'attr-name': { color: '#c76b29' },
    entity: { color: '#22a2c9' },
    url: { color: '#22a2c9' },
    'attr-value': { color: '#ac9739' },
    keyword: { color: '#ac9739' },
    control: { color: '#ac9739' },
    directive: { color: '#ac9739' },
    unit: { color: '#ac9739' },
    statement: { color: '#22a2c9' },
    regex: { color: '#22a2c9' },
    atrule: { color: '#22a2c9' },
    placeholder: { color: '#3d8fd1' },
    variable: { color: '#3d8fd1' },
    deleted: { textDecoration: 'line-through' },
    italic: { fontStyle: 'italic' },
    important: { fontWeight: 'bold', color: '#c94922' },
    bold: { fontWeight: 'bold' },
  },
});
