import { defineTheme } from './_helper.js';

export const coldarkCold = defineTheme({
  name: 'coldark-cold',
  type: 'light',
  base: {
    color: '#111b27',
    background: '#e3eaf2',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
  },
  palette: {
    comment: { color: '#3c526d' },
    prolog: { color: '#3c526d' },
    doctype: { color: '#3c526d' },
    cdata: { color: '#3c526d' },
    punctuation: { color: '#111b27' },
    tag: { color: '#006d6d' },
    'attr-name': { color: '#755f00' },
    boolean: { color: '#755f00' },
    number: { color: '#755f00' },
    constant: { color: '#755f00' },
    'class-name': { color: '#005a8e' },
    key: { color: '#005a8e' },
    parameter: { color: '#005a8e' },
    property: { color: '#005a8e' },
    'property-access': { color: '#005a8e' },
    variable: { color: '#005a8e' },
    'attr-value': { color: '#116b00' },
    inserted: { color: '#116b00' },
    color: { color: '#116b00' },
    string: { color: '#116b00' },
    builtin: { color: '#af00af' },
    package: { color: '#af00af' },
    regex: { color: '#af00af' },
    function: { color: '#7c00aa' },
    combinator: { color: '#a04900' },
    keyword: { color: '#a04900' },
    operator: { color: '#a04900' },
    'pseudo-class': { color: '#a04900' },
    'pseudo-element': { color: '#a04900' },
    selector: { color: '#a04900' },
    unit: { color: '#a04900' },
    deleted: { color: '#c22f2e' },
    important: { color: '#c22f2e', fontWeight: 'bold' },
    this: { color: '#005a8e', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
