import { defineTheme } from './_helper.js';

export const coldarkDark = defineTheme({
  name: 'coldark-dark',
  type: 'dark',
  base: {
    color: '#e3eaf2',
    background: '#111b27',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
  },
  palette: {
    comment: { color: '#8da1b9' },
    prolog: { color: '#8da1b9' },
    doctype: { color: '#8da1b9' },
    cdata: { color: '#8da1b9' },
    punctuation: { color: '#e3eaf2' },
    tag: { color: '#66cccc' },
    'attr-name': { color: '#e6d37a' },
    boolean: { color: '#e6d37a' },
    number: { color: '#e6d37a' },
    constant: { color: '#e6d37a' },
    'class-name': { color: '#6cb8e6' },
    key: { color: '#6cb8e6' },
    parameter: { color: '#6cb8e6' },
    property: { color: '#6cb8e6' },
    'property-access': { color: '#6cb8e6' },
    variable: { color: '#6cb8e6' },
    'attr-value': { color: '#91d076' },
    inserted: { color: '#91d076' },
    color: { color: '#91d076' },
    string: { color: '#91d076' },
    builtin: { color: '#f4adf4' },
    package: { color: '#f4adf4' },
    regex: { color: '#f4adf4' },
    function: { color: '#c699e3' },
    combinator: { color: '#e9ae7e' },
    keyword: { color: '#e9ae7e' },
    operator: { color: '#e9ae7e' },
    'pseudo-class': { color: '#e9ae7e' },
    'pseudo-element': { color: '#e9ae7e' },
    selector: { color: '#e9ae7e' },
    unit: { color: '#e9ae7e' },
    deleted: { color: '#cd6660' },
    important: { color: '#cd6660', fontWeight: 'bold' },
    this: { color: '#6cb8e6', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
