import { defineTheme } from './_helper.js';

export const coyWithoutShadows = defineTheme({
  name: 'coy-without-shadows',
  type: 'light',
  base: {
    color: 'black',
    background: 'none',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    position: 'relative',
    borderLeft: '10px solid #358ccb',
    boxShadow: '-1px 0 0 0 #358ccb, 0 0 0 1px #dfdfdf',
    backgroundColor: '#fdfdfd',
    margin: '.5em 0',
    padding: '0 1em',
  },
  palette: {
    comment: { color: '#7D8B99' },
    'block-comment': { color: '#7D8B99' },
    prolog: { color: '#7D8B99' },
    doctype: { color: '#7D8B99' },
    cdata: { color: '#7D8B99' },
    punctuation: { color: '#5F6364' },
    property: { color: '#c92c2c' },
    tag: { color: '#c92c2c' },
    boolean: { color: '#c92c2c' },
    number: { color: '#c92c2c' },
    'function-name': { color: '#c92c2c' },
    constant: { color: '#c92c2c' },
    symbol: { color: '#c92c2c' },
    deleted: { color: '#c92c2c' },
    selector: { color: '#2f9c0a' },
    'attr-name': { color: '#2f9c0a' },
    string: { color: '#2f9c0a' },
    char: { color: '#2f9c0a' },
    function: { color: '#2f9c0a' },
    builtin: { color: '#2f9c0a' },
    inserted: { color: '#2f9c0a' },
    operator: { color: '#a67f59' },
    entity: { color: '#a67f59' },
    url: { color: '#a67f59' },
    variable: { color: '#a67f59' },
    atrule: { color: '#1990b8' },
    'attr-value': { color: '#1990b8' },
    keyword: { color: '#1990b8' },
    'class-name': { color: '#1990b8' },
    regex: { color: '#e90' },
    important: { color: '#e90' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
