import { defineTheme } from './_helper.js';

export const dracula = defineTheme({
  name: 'dracula',
  type: 'dark',
  base: {
    color: '#f8f8f2',
    background: '#282a36',
    textShadow: '0 1px rgba(0, 0, 0, 0.3)',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    borderRadius: '0.3em',
  },
  palette: {
    comment: { color: '#6272a4' },
    prolog: { color: '#6272a4' },
    doctype: { color: '#6272a4' },
    cdata: { color: '#6272a4' },
    punctuation: { color: '#f8f8f2' },
    property: { color: '#ff79c6' },
    tag: { color: '#ff79c6' },
    constant: { color: '#ff79c6' },
    symbol: { color: '#ff79c6' },
    deleted: { color: '#ff79c6' },
    boolean: { color: '#bd93f9' },
    number: { color: '#bd93f9' },
    selector: { color: '#50fa7b' },
    'attr-name': { color: '#50fa7b' },
    string: { color: '#50fa7b' },
    char: { color: '#50fa7b' },
    builtin: { color: '#50fa7b' },
    inserted: { color: '#50fa7b' },
    operator: { color: '#f8f8f2' },
    entity: { color: '#f8f8f2' },
    url: { color: '#f8f8f2' },
    variable: { color: '#f8f8f2' },
    atrule: { color: '#f1fa8c' },
    'attr-value': { color: '#f1fa8c' },
    function: { color: '#f1fa8c' },
    'class-name': { color: '#f1fa8c' },
    keyword: { color: '#8be9fd' },
    regex: { color: '#ffb86c' },
    important: { color: '#ffb86c', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
