import { defineTheme } from './_helper.js';

export const duotoneEarth = defineTheme({
  name: 'duotone-earth',
  type: 'dark',
  base: {
    fontFamily:
      'Consolas, Menlo, Monaco, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", "Courier New", Courier, monospace',
    fontSize: '14px',
    lineHeight: '1.375',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    background: '#322d29',
    color: '#88786d',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
  },
  palette: {
    comment: { color: '#6a5f58' },
    prolog: { color: '#6a5f58' },
    doctype: { color: '#6a5f58' },
    cdata: { color: '#6a5f58' },
    punctuation: { color: '#6a5f58' },
    tag: { color: '#bfa05a' },
    operator: { color: '#bfa05a' },
    number: { color: '#bfa05a' },
    property: { color: '#88786d' },
    function: { color: '#88786d' },
    selector: { color: '#fff3eb' },
    'attr-name': { color: '#a48774' },
    boolean: { color: '#fcc440' },
    string: { color: '#fcc440' },
    entity: { color: '#fcc440' },
    url: { color: '#fcc440' },
    'attr-value': { color: '#fcc440' },
    keyword: { color: '#fcc440' },
    control: { color: '#fcc440' },
    directive: { color: '#fcc440' },
    unit: { color: '#fcc440' },
    statement: { color: '#fcc440' },
    regex: { color: '#fcc440' },
    atrule: { color: '#fcc440' },
    placeholder: { color: '#fcc440' },
    variable: { color: '#fcc440' },
    deleted: { textDecoration: 'line-through' },
    italic: { fontStyle: 'italic' },
    important: { fontWeight: 'bold', color: '#a48774' },
    bold: { fontWeight: 'bold' },
  },
});
