import { defineTheme } from './_helper.js';

const baseStyle = {
  fontFamily:
    'Consolas, Menlo, Monaco, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", "Courier New", Courier, monospace',
  fontSize: '14px',
  lineHeight: '1.375',
  direction: 'ltr' as const,
  textAlign: 'left' as const,
  whiteSpace: 'pre' as const,
  wordSpacing: 'normal',
  wordBreak: 'normal' as const,
  MozTabSize: '4',
  OTabSize: '4',
  tabSize: '4',
  WebkitHyphens: 'none' as const,
  MozHyphens: 'none' as const,
  hyphens: 'none' as const,
  padding: '1em',
  margin: '.5em 0',
  overflow: 'auto',
};

export const duotoneForest = defineTheme({
  name: 'duotone-forest',
  type: 'dark',
  base: {
    ...baseStyle,
    background: '#2a2d2a',
    color: '#687d68',
  },
  palette: {
    comment: { color: '#535f53' },
    prolog: { color: '#535f53' },
    doctype: { color: '#535f53' },
    cdata: { color: '#535f53' },
    punctuation: { color: '#535f53' },
    tag: { color: '#a2b34d' },
    operator: { color: '#a2b34d' },
    number: { color: '#a2b34d' },
    property: { color: '#687d68' },
    function: { color: '#687d68' },
    selector: { color: '#f0fff0' },
    'attr-name': { color: '#b3d6b3' },
    boolean: { color: '#e5fb79' },
    string: { color: '#e5fb79' },
    entity: { color: '#e5fb79' },
    url: { color: '#e5fb79' },
    'attr-value': { color: '#e5fb79' },
    keyword: { color: '#e5fb79' },
    control: { color: '#e5fb79' },
    directive: { color: '#e5fb79' },
    unit: { color: '#e5fb79' },
    statement: { color: '#e5fb79' },
    regex: { color: '#e5fb79' },
    atrule: { color: '#e5fb79' },
    placeholder: { color: '#e5fb79' },
    variable: { color: '#e5fb79' },
    deleted: { textDecoration: 'line-through' },
    italic: { fontStyle: 'italic' },
    important: { fontWeight: 'bold', color: '#b3d6b3' },
    bold: { fontWeight: 'bold' },
  },
});
