import { defineTheme } from './_helper.js';

export const holiTheme = defineTheme({
  name: 'holi-theme',
  type: 'dark',
  base: {},
  palette: {
    comment: { color: '#446e69' },
    prolog: { color: '#446e69' },
    doctype: { color: '#446e69' },
    cdata: { color: '#446e69' },
    punctuation: { color: '#d6b007' },
    property: { color: '#d6e7ff' },
    tag: { color: '#d6e7ff' },
    boolean: { color: '#d6e7ff' },
    number: { color: '#d6e7ff' },
    constant: { color: '#d6e7ff' },
    symbol: { color: '#d6e7ff' },
    deleted: { color: '#d6e7ff' },
    selector: { color: '#e60067' },
    'attr-name': { color: '#e60067' },
    builtin: { color: '#e60067' },
    inserted: { color: '#e60067' },
    string: { color: '#49c6ec' },
    char: { color: '#49c6ec' },
    operator: { color: '#ec8e01' },
    entity: { color: '#ec8e01' },
    url: { color: '#ec8e01' },
    atrule: { color: '#0fe468' },
    'attr-value': { color: '#0fe468' },
    keyword: { color: '#0fe468' },
    function: { color: '#78f3e9' },
    'class-name': { color: '#78f3e9' },
    regex: { color: '#d6e7ff' },
    important: { color: '#d6e7ff' },
    variable: { color: '#d6e7ff' },
  },
});
