import { defineTheme } from './_helper.js';

export const laserwave = defineTheme({
  name: 'laserwave',
  type: 'dark',
  base: {
    background: '#27212e',
    color: '#ffffff',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '1em',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
    borderRadius: '0.5em',
  },
  palette: {
    comment: { color: '#91889b' },
    prolog: { color: '#91889b' },
    cdata: { color: '#91889b' },
    punctuation: { color: '#7b6995' },
    builtin: { color: '#ffe261' },
    constant: { color: '#ffe261' },
    boolean: { color: '#ffe261' },
    number: { color: '#b381c5' },
    important: { color: '#40b4c4' },
    atrule: { color: '#40b4c4' },
    property: { color: '#40b4c4' },
    keyword: { color: '#40b4c4' },
    doctype: { color: '#74dfc4' },
    operator: { color: '#74dfc4' },
    inserted: { color: '#74dfc4' },
    tag: { color: '#74dfc4' },
    'class-name': { color: '#74dfc4' },
    symbol: { color: '#74dfc4' },
    'attr-name': { color: '#eb64b9' },
    function: { color: '#eb64b9' },
    deleted: { color: '#eb64b9' },
    selector: { color: '#eb64b9' },
    'attr-value': { color: '#b4dce7' },
    regex: { color: '#b4dce7' },
    char: { color: '#b4dce7' },
    string: { color: '#b4dce7' },
    entity: { color: '#ffffff' },
    url: { color: '#ffffff' },
    variable: { color: '#ffffff' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
