import { defineTheme } from './_helper.js';

export const materialLight = defineTheme({
  name: 'material-light',
  type: 'light',
  base: {
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    color: '#90a4ae',
    background: '#fafafa',
    fontFamily: 'Roboto Mono, monospace',
    fontSize: '1em',
    lineHeight: '1.5em',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    overflow: 'auto',
    position: 'relative',
    margin: '0.5em 0',
    padding: '1.25em 1em',
  },
  palette: {
    atrule: { color: '#7c4dff' },
    'attr-name': { color: '#39adb5' },
    'attr-value': { color: '#f6a434' },
    attribute: { color: '#f6a434' },
    boolean: { color: '#7c4dff' },
    builtin: { color: '#39adb5' },
    cdata: { color: '#39adb5' },
    char: { color: '#39adb5' },
    class: { color: '#39adb5' },
    'class-name': { color: '#6182b8' },
    comment: { color: '#aabfc9' },
    constant: { color: '#7c4dff' },
    deleted: { color: '#e53935' },
    doctype: { color: '#aabfc9' },
    entity: { color: '#e53935' },
    function: { color: '#7c4dff' },
    hexcode: { color: '#f76d47' },
    id: { color: '#7c4dff', fontWeight: 'bold' },
    important: { color: '#7c4dff', fontWeight: 'bold' },
    inserted: { color: '#39adb5' },
    keyword: { color: '#7c4dff' },
    number: { color: '#f76d47' },
    operator: { color: '#39adb5' },
    prolog: { color: '#aabfc9' },
    property: { color: '#39adb5' },
    'pseudo-class': { color: '#f6a434' },
    'pseudo-element': { color: '#f6a434' },
    punctuation: { color: '#39adb5' },
    regex: { color: '#6182b8' },
    selector: { color: '#e53935' },
    string: { color: '#f6a434' },
    symbol: { color: '#7c4dff' },
    tag: { color: '#e53935' },
    unit: { color: '#f76d47' },
    url: { color: '#e53935' },
    variable: { color: '#e53935' },
  },
});
