import { defineTheme } from './_helper.js';

export const oneLight = defineTheme({
  name: 'one-light',
  type: 'light',
  base: {
    background: 'hsl(230, 1%, 98%)',
    color: 'hsl(230, 8%, 24%)',
    fontFamily:
      '"Fira Code", "Fira Mono", Menlo, Consolas, "DejaVu Sans Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
    borderRadius: '0.3em',
  },
  palette: {
    comment: { color: 'hsl(230, 4%, 64%)', fontStyle: 'italic' },
    prolog: { color: 'hsl(230, 4%, 64%)' },
    cdata: { color: 'hsl(230, 4%, 64%)' },
    doctype: { color: 'hsl(230, 8%, 24%)' },
    punctuation: { color: 'hsl(230, 8%, 24%)' },
    entity: { color: 'hsl(230, 8%, 24%)' },
    'attr-name': { color: 'hsl(35, 99%, 36%)' },
    'class-name': { color: 'hsl(35, 99%, 36%)' },
    boolean: { color: 'hsl(35, 99%, 36%)' },
    constant: { color: 'hsl(35, 99%, 36%)' },
    number: { color: 'hsl(35, 99%, 36%)' },
    atrule: { color: 'hsl(35, 99%, 36%)' },
    keyword: { color: 'hsl(301, 63%, 40%)' },
    property: { color: 'hsl(5, 74%, 59%)' },
    tag: { color: 'hsl(5, 74%, 59%)' },
    symbol: { color: 'hsl(5, 74%, 59%)' },
    deleted: { color: 'hsl(5, 74%, 59%)' },
    important: { color: 'hsl(5, 74%, 59%)' },
    selector: { color: 'hsl(119, 34%, 47%)' },
    string: { color: 'hsl(119, 34%, 47%)' },
    char: { color: 'hsl(119, 34%, 47%)' },
    builtin: { color: 'hsl(119, 34%, 47%)' },
    inserted: { color: 'hsl(119, 34%, 47%)' },
    regex: { color: 'hsl(119, 34%, 47%)' },
    'attr-value': { color: 'hsl(119, 34%, 47%)' },
    variable: { color: 'hsl(221, 87%, 60%)' },
    operator: { color: 'hsl(221, 87%, 60%)' },
    function: { color: 'hsl(221, 87%, 60%)' },
    url: { color: 'hsl(198, 99%, 37%)' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
