import { defineTheme } from './_helper.js';

export const pojoaque = defineTheme({
  name: 'pojoaque',
  type: 'dark',
  base: {
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    wordWrap: 'break-word',
    fontFamily: 'Menlo, Monaco, "Courier New", monospace',
    fontSize: '15px',
    lineHeight: '1.5',
    color: '#DCCF8F',
    textShadow: '0',
    borderRadius: '5px',
    border: '1px solid #000',
    background: '#181914',
    padding: '12px',
    overflow: 'auto',
  },
  palette: {
    comment: { color: '#586e75', fontStyle: 'italic' },
    prolog: { color: '#586e75', fontStyle: 'italic' },
    doctype: { color: '#586e75', fontStyle: 'italic' },
    cdata: { color: '#586e75', fontStyle: 'italic' },
    number: { color: '#b89859' },
    string: { color: '#468966' },
    char: { color: '#468966' },
    builtin: { color: '#468966' },
    inserted: { color: '#468966' },
    'attr-name': { color: '#b89859' },
    operator: { color: '#dccf8f' },
    entity: { color: '#dccf8f' },
    url: { color: '#dccf8f' },
    selector: { color: '#859900' },
    regex: { color: '#859900' },
    atrule: { color: '#cb4b16' },
    keyword: { color: '#cb4b16' },
    'attr-value': { color: '#468966' },
    function: { color: '#b58900' },
    variable: { color: '#b58900' },
    placeholder: { color: '#b58900' },
    property: { color: '#b89859' },
    tag: { color: '#ffb03b' },
    boolean: { color: '#b89859' },
    constant: { color: '#b89859' },
    symbol: { color: '#b89859' },
    important: { color: '#dc322f' },
    statement: { color: '#dc322f' },
    deleted: { color: '#dc322f' },
    punctuation: { color: '#dccf8f' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
  },
});
