import { defineTheme } from './_helper.js';

export const shadesOfPurple = defineTheme({
  name: 'shades-of-purple',
  type: 'dark',
  base: {},
  palette: {
    comment: { color: '#b362ff' },
    prolog: { color: '#b362ff' },
    cdata: { color: '#b362ff' },
    delimiter: { color: '#ff9d00' },
    keyword: { color: '#ff9d00' },
    selector: { color: '#ff9d00' },
    important: { color: '#ff9d00' },
    atrule: { color: '#ff9d00' },
    operator: { color: 'rgb(255, 180, 84)' },
    'attr-name': { color: 'rgb(255, 180, 84)' },
    punctuation: { color: '#ffffff' },
    boolean: { color: 'rgb(255, 98, 140)' },
    tag: { color: 'rgb(255, 157, 0)' },
    doctype: { color: 'rgb(255, 157, 0)' },
    builtin: { color: 'rgb(255, 157, 0)' },
    entity: { color: '#6897bb' },
    symbol: { color: '#6897bb' },
    number: { color: '#ff628c' },
    property: { color: '#ff628c' },
    constant: { color: '#ff628c' },
    variable: { color: '#ff628c' },
    string: { color: '#a5ff90' },
    char: { color: '#a5ff90' },
    'attr-value': { color: '#a5c261' },
    url: { color: '#287bde', textDecoration: 'underline' },
    function: { color: 'rgb(250, 208, 0)' },
    regex: { background: '#364135' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    inserted: { background: '#00ff00' },
    deleted: { background: '#ff000d' },
    'class-name': { color: '#fb94ff' },
  },
});
