import { defineTheme } from './_helper.js';

export const synthwave84 = defineTheme({
  name: 'synthwave-84',
  type: 'dark',
  base: {
    color: '#f92aad',
    textShadow: '0 0 2px #100c0f, 0 0 5px #dc078e33, 0 0 10px #fff3',
    background: 'none',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    backgroundColor: 'transparent',
    backgroundImage: 'linear-gradient(to bottom, #2a2139 75%, #34294f)',
  },
  palette: {
    comment: { color: '#8e8e8e' },
    'block-comment': { color: '#8e8e8e' },
    prolog: { color: '#8e8e8e' },
    doctype: { color: '#8e8e8e' },
    cdata: { color: '#8e8e8e' },
    punctuation: { color: '#ccc' },
    tag: { color: '#e2777a' },
    'attr-name': { color: '#e2777a' },
    namespace: { color: '#e2777a' },
    number: { color: '#e2777a' },
    unit: { color: '#e2777a' },
    hexcode: { color: '#e2777a' },
    deleted: { color: '#e2777a' },
    property: { color: '#72f1b8' },
    selector: { color: '#72f1b8' },
    'function-name': { color: '#6196cc' },
    boolean: { color: '#fdfdfd' },
    function: { color: '#fdfdfd' },
    'class-name': { color: '#fff5f6' },
    constant: { color: '#f92aad' },
    symbol: { color: '#f92aad' },
    important: { color: '#f4eee4', fontWeight: 'bold' },
    atrule: { color: '#f4eee4' },
    keyword: { color: '#f4eee4' },
    builtin: { color: '#f4eee4' },
    string: { color: '#f87c32' },
    char: { color: '#f87c32' },
    'attr-value': { color: '#f87c32' },
    regex: { color: '#f87c32' },
    variable: { color: '#f87c32' },
    operator: { color: '#67cdcc' },
    entity: { color: '#67cdcc' },
    url: { color: '#67cdcc' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    inserted: { color: 'green' },
  },
});
