import { defineTheme } from './_helper.js';

export const vs = defineTheme({
  name: 'vs',
  type: 'light',
  base: {
    color: '#393A34',
    fontFamily:
      '"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    fontSize: '.9em',
    lineHeight: '1.2em',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    border: '1px solid #dddddd',
    backgroundColor: 'white',
  },
  palette: {
    comment: { color: '#008000', fontStyle: 'italic' },
    prolog: { color: '#008000', fontStyle: 'italic' },
    doctype: { color: '#008000', fontStyle: 'italic' },
    cdata: { color: '#008000', fontStyle: 'italic' },
    string: { color: '#A31515' },
    punctuation: { color: '#393A34' },
    operator: { color: '#393A34' },
    url: { color: '#36acaa' },
    symbol: { color: '#36acaa' },
    number: { color: '#36acaa' },
    boolean: { color: '#36acaa' },
    variable: { color: '#36acaa' },
    constant: { color: '#36acaa' },
    inserted: { color: '#36acaa' },
    atrule: { color: '#0000ff' },
    keyword: { color: '#0000ff' },
    'attr-value': { color: '#0000ff' },
    function: { color: '#393A34' },
    deleted: { color: '#9a050f' },
    selector: { color: '#800000' },
    important: { color: '#e90', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    'class-name': { color: '#2B91AF' },
    tag: { color: '#800000' },
    'attr-name': { color: '#ff0000' },
    property: { color: '#ff0000' },
    regex: { color: '#ff0000' },
    entity: { color: '#ff0000' },
  },
});
