import { defineTheme } from './_helper.js';

export const vscDarkPlus = defineTheme({
  name: 'vsc-dark-plus',
  type: 'dark',
  base: {
    color: '#d4d4d4',
    fontSize: '13px',
    textShadow: 'none',
    fontFamily:
      'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", "Courier New", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    background: '#1e1e1e',
  },
  palette: {
    comment: { color: '#6a9955' },
    prolog: { color: '#6a9955' },
    punctuation: { color: '#d4d4d4' },
    property: { color: '#9cdcfe' },
    tag: { color: '#569cd6' },
    boolean: { color: '#569cd6' },
    number: { color: '#b5cea8' },
    constant: { color: '#9cdcfe' },
    symbol: { color: '#b5cea8' },
    inserted: { color: '#b5cea8' },
    unit: { color: '#b5cea8' },
    selector: { color: '#d7ba7d' },
    'attr-name': { color: '#9cdcfe' },
    string: { color: '#ce9178' },
    char: { color: '#ce9178' },
    builtin: { color: '#ce9178' },
    deleted: { color: '#ce9178' },
    operator: { color: '#d4d4d4' },
    entity: { color: '#569cd6' },
    atrule: { color: '#ce9178' },
    keyword: { color: '#569CD6' },
    function: { color: '#dcdcaa' },
    regex: { color: '#d16969' },
    important: { color: '#569cd6' },
    italic: { fontStyle: 'italic' },
    'class-name': { color: '#4ec9b0' },
    'maybe-class-name': { color: '#4ec9b0' },
    console: { color: '#9cdcfe' },
    parameter: { color: '#9cdcfe' },
    interpolation: { color: '#9cdcfe' },
    variable: { color: '#9cdcfe' },
    escape: { color: '#d7ba7d' },
    cdata: { color: '#808080' },
    'attr-value': { color: '#ce9178' },
    namespace: { color: '#4ec9b0' },
  },
});
