import { defineTheme } from './_helper.js';

export const xonokai = defineTheme({
  name: 'xonokai',
  type: 'dark',
  base: {
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    hyphens: 'none',
    whiteSpace: 'pre-wrap',
    wordWrap: 'normal',
    fontFamily: 'Menlo, Monaco, "Courier New", monospace',
    fontSize: '14px',
    color: '#76d9e6',
    textShadow: 'none',
    background: '#2a2a2a',
    padding: '15px',
    borderRadius: '4px',
    border: '1px solid #e1e1e8',
    overflow: 'auto',
    position: 'relative',
  },
  palette: {
    comment: { color: '#6f705e' },
    prolog: { color: '#6f705e' },
    doctype: { color: '#6f705e' },
    cdata: { color: '#6f705e' },
    operator: { color: '#a77afe' },
    boolean: { color: '#a77afe' },
    number: { color: '#a77afe' },
    'attr-name': { color: '#e6d06c' },
    string: { color: '#e6d06c' },
    entity: { color: '#e6d06c' },
    url: { color: '#e6d06c' },
    selector: { color: '#a6e22d' },
    inserted: { color: '#a6e22d' },
    atrule: { color: '#ef3b7d' },
    'attr-value': { color: '#ef3b7d' },
    keyword: { color: '#ef3b7d' },
    important: { color: '#ef3b7d', fontWeight: 'bold' },
    deleted: { color: '#ef3b7d' },
    regex: { color: '#76d9e6' },
    statement: { color: '#76d9e6', fontWeight: 'bold' },
    placeholder: { color: '#fff' },
    variable: { color: '#fff' },
    bold: { fontWeight: 'bold' },
    punctuation: { color: '#bebec5' },
    italic: { fontStyle: 'italic' },
  },
});
