import { ESLint } from "eslint";

import { noAccentColor, noBase64Images, noAnimation, noAspectRatio, noBorderInlineBlockIndividual, noBorderInlineBlockLonghand, noBorderInlineBlock, noBorderRadiusLogical, noBoxShadow, noClipPath, noColumnLayoutProperties, noConicGradient, noFlexWrap, noFunctionClamp, noFunctionMax, noFunctionMin, noGap, noGridTemplate, noHyphens, noImportant, noBlockInlineSize, noIntrinsicSize, noMarginBlockStartEnd, noMarginInlineBlock, noMarginInlineStartEnd, noMaxBlockSize, noMinInlineSize, noModernColor, noOutlineOffset, noOverflowWrap, noPaddingBlockStartEnd, noPaddingInlineBlock, noPaddingInlineStartEnd, noPosition, noScrollSnap, noTabSize, noTextAlignLast, noTextDecorationThickness, noTextEmphasisPosition, noTextEmphasis, noTextUnderlineOffset, noWordBreak } from "./rules";

export default {
  rules: {
    'no-accent-color': noAccentColor,
    'no-animation': noAnimation,
    'no-aspect-ratio': noAspectRatio,
    'no-border-inline-block-logicals': noBorderInlineBlockIndividual,
    'no-border-inline-block-longhand': noBorderInlineBlockLonghand,
    'no-border-inline-block': noBorderInlineBlock,
    'no-border-radius-logicals': noBorderRadiusLogical,
    'no-box-shadow': noBoxShadow,
    'no-base64-images': noBase64Images,
    'no-clip-path': noClipPath,
    'no-column-layout-properties': noColumnLayoutProperties,
    'no-conic-gradient': noConicGradient,
    'no-flex-wrap': noFlexWrap,
    'no-function-clamp': noFunctionClamp,
    'no-function-max': noFunctionMax,
    'no-function-min': noFunctionMin,
    'no-gap': noGap,
    'no-grid-template': noGridTemplate,
    'no-hyphens': noHyphens,
    'no-important': noImportant,
    'no-block-inline-size': noBlockInlineSize,
    'no-intrinsic-size': noIntrinsicSize,
    'no-margin-block-start-end': noMarginBlockStartEnd,
    'no-margin-inline-block': noMarginInlineBlock,
    'no-margin-inline-start-end': noMarginInlineStartEnd,
    'no-max-block-size': noMaxBlockSize,
    'no-min-inline-size': noMinInlineSize,
    'no-modern-color': noModernColor,
    'no-outline-offset': noOutlineOffset,
    'no-overflow-wrap': noOverflowWrap,
    'no-padding-block-start-end': noPaddingBlockStartEnd,
    'no-padding-inline-block': noPaddingInlineBlock,
    'no-padding-inline-start-end': noPaddingInlineStartEnd,
    'no-position': noPosition,
    'no-scroll-snap': noScrollSnap,
    'no-tab-size': noTabSize,
    'no-text-align-last': noTextAlignLast,
    'no-text-decoration-thickness': noTextDecorationThickness,
    'no-text-emphasis-position': noTextEmphasisPosition,
    'no-text-emphasis': noTextEmphasis,
    'no-text-underline-offset': noTextUnderlineOffset,
    'no-word-break': noWordBreak,
  },
} satisfies ESLint.Plugin;
