name: Bump
on:
  push:
    branches:
      - canary
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  bump:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions: 
      contents: write
      pull-requests: write
    container:
      image: node:22
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 1
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: pnpm setup
        uses: pnpm/action-setup@738f428026a1f5a72398de22aeed83d859c4a660
      - name: Install packages
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Create "version packages" pull request
        uses: changesets/action@2ae596f3dd74aaee4f346b31fda33a58528d3d40
        with:
          version: pnpm run version
          title: "chore(root): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
