name: Bump
on:
  push:
    branches:
      - canary
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  bump:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions: 
      contents: write
      pull-requests: write
    container:
      image: node:22
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 1
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: pnpm setup
        uses: pnpm/action-setup@9b5745cdf0a2e8c2620f0746130f809adb911c19
      - name: Install packages
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Create "version packages" pull request
        uses: changesets/action@a7c500273b5be4fb897d21ceededa4767223a843
        with:
          version: pnpm run version
          title: "chore(root): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
