name: Lint
on:
  push:
    branches:
      - main
      - canary
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    runs-on:
      size: 2x8
      image: ${{ vars.DEPOT_ORG_ID }}.registry.depot.dev/react-email-ci:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 1
      - name: Install packages
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
