name: Pin Dependencies Check
on:
  push:
    branches:
      - main
      - canary
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: read
jobs:
  pin-dependencies-check:
    runs-on: depot-ubuntu-22.04-32
    container:
      image: node:22-slim
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 1
      - name: pnpm setup
        uses: pnpm/action-setup@738f428026a1f5a72398de22aeed83d859c4a660
      - name: Install root dependencies only
        run: pnpm install --frozen-lockfile --filter . --ignore-scripts
      - name: Check for pinned dependencies
        run: pnpm exec tsx ./scripts/check-dependency-versions.ts
