name: Pull Request Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  pull-request-title-check:
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run PR title check
        run: |
          npx tsx ./scripts/pr-title-check.ts
