name: rsnd

on:
  push:
    branches:
      - main


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: version
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: pnpm setup
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: pnpm Cache
        id: pnpm-cache
        uses: buildjet/cache@3e70d19e31d6a8030aeddf6ed8dbe601f94d09f4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install packages
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Exit prerelease mode
        # This step errors if it is not in prerelease mode
        continue-on-error: true
        run: pnpm canary:exit

      - name: Create Release Pull Request
        uses: changesets/action@5f15b43b429db9083a86b852c3a1b3a6973e8225
        with:
          version: pnpm run version
          title: "chore(root): Version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
